---
- name: Ensure Alertmanager config directory exists
file:
path: /etc/alertmanager
state: directory

- name: Deploy Alertmanager template with Slack Webhook
template:
src: alertmanager.yml.j2
dest: /etc/alertmanager/alertmanager.yml
