---
- name: Configure Kubernetes Cluster Nodes & Monitoring Stack
  hosts: localhost
  connection: local
  become: yes
  roles:
    - node-setup
    - node-exporter
    - prometheus-config
    - alertmanager-config
