---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install system dependencies
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Ensure containerd service is active and enabled
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
